// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjHhxSg8Nc3LIjfxL4UQ19yjJg4EwrD7c',
    appId: '1:487858724060:web:a08f3fc217df1e5737a819',
    messagingSenderId: '487858724060',
    projectId: 'chatkoko-ae3f0',
    authDomain: 'chatkoko-ae3f0.firebaseapp.com',
    storageBucket: 'chatkoko-ae3f0.firebasestorage.app',
    measurementId: 'G-VCFEWVM1E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa7qlDqLpBjXtP1Qo7bvJsuCcmSxGaVvE',
    appId: '1:487858724060:android:8575eaeb1cfef3b137a819',
    messagingSenderId: '487858724060',
    projectId: 'chatkoko-ae3f0',
    storageBucket: 'chatkoko-ae3f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl6VZqiCvxB3pVgR_RpZkdDQW9iTzhel0',
    appId: '1:487858724060:ios:eb6c8b2f55600b0437a819',
    messagingSenderId: '487858724060',
    projectId: 'chatkoko-ae3f0',
    storageBucket: 'chatkoko-ae3f0.firebasestorage.app',
    androidClientId: '487858724060-5rusjmg149sm7o8279nfgbli7tc0hcep.apps.googleusercontent.com',
    iosClientId: '487858724060-dv4np1ks9ecke24rd1bp456gqdtu421t.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatkoko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl6VZqiCvxB3pVgR_RpZkdDQW9iTzhel0',
    appId: '1:487858724060:ios:eb6c8b2f55600b0437a819',
    messagingSenderId: '487858724060',
    projectId: 'chatkoko-ae3f0',
    storageBucket: 'chatkoko-ae3f0.firebasestorage.app',
    androidClientId: '487858724060-5rusjmg149sm7o8279nfgbli7tc0hcep.apps.googleusercontent.com',
    iosClientId: '487858724060-dv4np1ks9ecke24rd1bp456gqdtu421t.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatkoko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjHhxSg8Nc3LIjfxL4UQ19yjJg4EwrD7c',
    appId: '1:487858724060:web:548b7a2e129595a837a819',
    messagingSenderId: '487858724060',
    projectId: 'chatkoko-ae3f0',
    authDomain: 'chatkoko-ae3f0.firebaseapp.com',
    storageBucket: 'chatkoko-ae3f0.firebasestorage.app',
    measurementId: 'G-Z82W25P9RC',
  );

}